[package]
name = "grass"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 0

[dependencies]
bevy = { version = "0.12.1", features = ["jpeg"] }
bevy_xpbd_3d = "0.3.3"
bytemuck = "1.14.0"
fastrand = "2.0.1"
noise = "0.8.2"
rand = "0.8.5"
rand_distr = "0.4.3"
wgpu = "0.18.0"
